name: 'ftl-file-checker'
description: 'validate flow-token-list pr files'
with:
  tokenJsonSchemaPath:
    description: 'json schema of token.json'
    required: true
    default: 'src/schemas/token.schema.json'
runs:
  using: 'node16'
  main: 'dist/index.js'