name: 'ftl-file-checker'
description: 'validate flow-token-list pr files'
inputs:
  TOKEN_JSON_SCHEMA_PATH:
    description: 'json schema of token.json'
    required: true
    default: 'src/schemas/token.schema.json'
  VALIDATE_IMAGES:
    description: 'validate image size or not'
    required: true
    default: true
  IMAGE_MAX_SIZE:
    description: 'allowed max image size'
    required: true
    default: 20000
runs:
  using: 'node16'
  main: 'dist/index.js'